"""initial schema

Revision ID: 1b8b48d228fb
Revises: 6a2f0ee5965c
Create Date: 2026-03-24 18:32:52.833290
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '1b8b48d228fb'
down_revision: Union[str, None] = '6a2f0ee5965c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
