"""add image_url to affiliate_links

Revision ID: 35f72867cadd
Revises: 1b8b48d228fb
Create Date: 2026-04-10 10:59:38.876922
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '35f72867cadd'
down_revision: Union[str, None] = '1b8b48d228fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affiliate_links', sa.Column('image_url', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('affiliate_links', 'image_url')
    # ### end Alembic commands ###
