"""initial schema

Revision ID: 6a2f0ee5965c
Revises: 799341299910
Create Date: 2026-03-24 18:25:36.034251
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '6a2f0ee5965c'
down_revision: Union[str, None] = '799341299910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
