"""initial schema

Revision ID: 799341299910
Revises: 
Create Date: 2026-03-24 18:13:37.479568
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '799341299910'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_logs_agent_name', 'agent_logs', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_logs_id'), 'agent_logs', ['id'], unique=False)
    op.create_index('ix_agent_logs_timestamp', 'agent_logs', ['timestamp'], unique=False)
    op.create_table('niches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subdomain', sa.String(length=100), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('go_no_go', sa.String(length=10), nullable=True),
    sa.Column('recommended_budget', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('subdomain')
    )
    op.create_index('ix_niches_created_at', 'niches', ['created_at'], unique=False)
    op.create_index('ix_niches_go_no_go', 'niches', ['go_no_go'], unique=False)
    op.create_index(op.f('ix_niches_id'), 'niches', ['id'], unique=False)
    op.create_index('ix_niches_status', 'niches', ['status'], unique=False)
    op.create_table('affiliate_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('niche_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=500), nullable=False),
    sa.Column('asin', sa.String(length=20), nullable=True),
    sa.Column('link_url', sa.String(length=1000), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_links_id'), 'affiliate_links', ['id'], unique=False)
    op.create_index('ix_affiliate_links_niche_id', 'affiliate_links', ['niche_id'], unique=False)
    op.create_index('ix_affiliate_links_status', 'affiliate_links', ['status'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('niche_id', sa.Integer(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index('ix_alerts_niche_id', 'alerts', ['niche_id'], unique=False)
    op.create_index('ix_alerts_resolved', 'alerts', ['resolved'], unique=False)
    op.create_index('ix_alerts_severity', 'alerts', ['severity'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('niche_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_id'), 'approvals', ['id'], unique=False)
    op.create_index('ix_approvals_niche_id', 'approvals', ['niche_id'], unique=False)
    op.create_index('ix_approvals_status', 'approvals', ['status'], unique=False)
    op.create_table('budget_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('niche_id', sa.Integer(), nullable=False),
    sa.Column('allocated', sa.Float(), nullable=False),
    sa.Column('spent', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_allocations_id'), 'budget_allocations', ['id'], unique=False)
    op.create_index('ix_budget_allocations_niche_id', 'budget_allocations', ['niche_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('niche_id', sa.Integer(), nullable=False),
    sa.Column('google_campaign_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('cpc', sa.Float(), nullable=True),
    sa.Column('ctr', sa.Float(), nullable=True),
    sa.Column('roas', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_campaign_id')
    )
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_index('ix_campaigns_niche_id', 'campaigns', ['niche_id'], unique=False)
    op.create_index('ix_campaigns_status', 'campaigns', ['status'], unique=False)
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('niche_id', sa.Integer(), nullable=False),
    sa.Column('page_type', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pages_id'), 'pages', ['id'], unique=False)
    op.create_index('ix_pages_niche_id', 'pages', ['niche_id'], unique=False)
    op.create_index('ix_pages_status', 'pages', ['status'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pages_status', table_name='pages')
    op.drop_index('ix_pages_niche_id', table_name='pages')
    op.drop_index(op.f('ix_pages_id'), table_name='pages')
    op.drop_table('pages')
    op.drop_index('ix_campaigns_status', table_name='campaigns')
    op.drop_index('ix_campaigns_niche_id', table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index('ix_budget_allocations_niche_id', table_name='budget_allocations')
    op.drop_index(op.f('ix_budget_allocations_id'), table_name='budget_allocations')
    op.drop_table('budget_allocations')
    op.drop_index('ix_approvals_status', table_name='approvals')
    op.drop_index('ix_approvals_niche_id', table_name='approvals')
    op.drop_index(op.f('ix_approvals_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index('ix_alerts_severity', table_name='alerts')
    op.drop_index('ix_alerts_resolved', table_name='alerts')
    op.drop_index('ix_alerts_niche_id', table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_affiliate_links_status', table_name='affiliate_links')
    op.drop_index('ix_affiliate_links_niche_id', table_name='affiliate_links')
    op.drop_index(op.f('ix_affiliate_links_id'), table_name='affiliate_links')
    op.drop_table('affiliate_links')
    op.drop_index('ix_niches_status', table_name='niches')
    op.drop_index(op.f('ix_niches_id'), table_name='niches')
    op.drop_index('ix_niches_go_no_go', table_name='niches')
    op.drop_index('ix_niches_created_at', table_name='niches')
    op.drop_table('niches')
    op.drop_index('ix_agent_logs_timestamp', table_name='agent_logs')
    op.drop_index(op.f('ix_agent_logs_id'), table_name='agent_logs')
    op.drop_index('ix_agent_logs_agent_name', table_name='agent_logs')
    op.drop_table('agent_logs')
    # ### end Alembic commands ###
